# Generated by Django 5.0 on 2023-12-13 15:36

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='interested_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture',
            field=models.URLField(blank=True, help_text='Dog picture url', null=True, validators=[django.core.validators.RegexValidator('^https://i.imgur.com//.*$')]),
        ),
    ]
