# Generated by Django 5.0 on 2023-12-09 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='picture',
            field=models.CharField(max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
