# Generated by Django 5.0 on 2023-12-13 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_interested_users_alter_dog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture',
            field=models.URLField(blank=True, help_text='Dog picture url', null=True, validators=[django.core.validators.RegexValidator('^https://i.imgur.com//.*$', message='Image must have prefix https://i.imgur.com/')]),
        ),
    ]
