# Generated by Django 5.0 on 2023-12-13 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_dog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='picture',
            field=models.CharField(blank=True, help_text='Dog picture url', max_length=200, null=True, validators=[django.core.validators.RegexValidator('^https://i.imgur.com/.*$', message='Image must have prefix https://i.imgur.com/')]),
        ),
    ]
