# Generated by Django 5.0 on 2023-12-16 15:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_alter_dog_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='interested_users',
        ),
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Dog description', validators=[django.core.validators.RegexValidator(message='Dog description cannot contain invalid characters.', regex='^[a-zA-Z0-9,;. \\-\\t?!]*$'), django.core.validators.MaxLengthValidator(400)]),
        ),
        migrations.AlterField(
            model_name='dog',
            name='picture',
            field=models.CharField(blank=True, default='', help_text='Dog picture url', max_length=200, validators=[django.core.validators.RegexValidator('^https://i.imgur.com/.*$', message='Image must have prefix https://i.imgur.com/')]),
        ),
        migrations.CreateModel(
            name='FavouriteDog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
