# Generated by Django 5.0 on 2023-12-16 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0006_remove_dog_interested_users_alter_dog_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favouritedog',
            constraint=models.UniqueConstraint(fields=('user', 'dog'), name='unique-favourites'),
        ),
    ]
