# Generated by Django 5.0 on 2023-12-17 12:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_remove_favouritedog_unique_favourites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(default='Unnamed', help_text='Dog name', max_length=20, validators=[django.core.validators.RegexValidator(message='Dog name cannot contain invalid characters and must only have an uppercase character at the start.', regex='^[A-Z][a-z]+$'), django.core.validators.MinLengthValidator(2)]),
        ),
    ]
